create table if not exists public.public_channel_member_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  chat_id bigint not null,
  chat_username text,
  chat_title text,
  user_id bigint not null,
  username text,
  display_name text,
  is_bot boolean not null default false,
  joined boolean not null default true,
  decision text not null,
  analysis_mode text,
  score integer,
  reasons text[] not null default '{}'::text[],
  strong_signals text[] not null default '{}'::text[],
  profile_photos integer,
  raw_update jsonb not null default '{}'::jsonb
);

alter table public.public_channel_member_audit enable row level security;

create index if not exists public_channel_member_audit_created_at_idx
  on public.public_channel_member_audit (created_at desc);

create index if not exists public_channel_member_audit_chat_id_idx
  on public.public_channel_member_audit (chat_id, created_at desc);

create index if not exists public_channel_member_audit_user_id_idx
  on public.public_channel_member_audit (user_id, created_at desc);

create index if not exists public_channel_member_audit_decision_idx
  on public.public_channel_member_audit (decision, created_at desc);
