-- Add a non-destructive editorial lifecycle and administrable SEO metadata.
-- Existing rows remain published and active to preserve the current catalog.

alter table public.series
  add column if not exists status text not null default 'published',
  add column if not exists is_active boolean not null default true,
  add column if not exists is_new boolean not null default false,
  add column if not exists content_delivery_type text not null default 'telegram',
  add column if not exists currency text not null default 'BRL',
  add column if not exists price_cents integer,
  add column if not exists published_at timestamptz,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists canonical_url text,
  add column if not exists og_title text,
  add column if not exists og_description text,
  add column if not exists og_image_url text,
  add column if not exists seo_noindex boolean not null default false;

update public.series
set
  status = coalesce(nullif(lower(trim(status)), ''), 'published'),
  is_active = coalesce(is_active, true),
  currency = 'BRL',
  price_cents = greatest(0, round(coalesce(price, 0)::numeric * 100)::integer),
  published_at = coalesce(published_at, created_at, now())
where
  price_cents is null
  or published_at is null
  or currency is distinct from 'BRL';

alter table public.series
  alter column price_cents set default 0,
  alter column price_cents set not null,
  drop constraint if exists series_editorial_status_check,
  add constraint series_editorial_status_check
    check (status in ('draft', 'published', 'hidden', 'archived')),
  drop constraint if exists series_delivery_type_check,
  add constraint series_delivery_type_check
    check (content_delivery_type in ('telegram', 'web', 'hybrid')),
  drop constraint if exists series_currency_check,
  add constraint series_currency_check
    check (currency = 'BRL'),
  drop constraint if exists series_price_cents_check,
  add constraint series_price_cents_check
    check (price_cents >= 0),
  drop constraint if exists series_seo_title_length_check,
  add constraint series_seo_title_length_check
    check (seo_title is null or char_length(seo_title) <= 70),
  drop constraint if exists series_seo_description_length_check,
  add constraint series_seo_description_length_check
    check (seo_description is null or char_length(seo_description) <= 180);

create or replace function public.sync_series_price_fields()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    if new.price_cents is null then
      new.price_cents := greatest(0, round(coalesce(new.price, 0)::numeric * 100)::integer);
    else
      new.price := new.price_cents::numeric / 100;
    end if;
  elsif new.price_cents is distinct from old.price_cents then
    new.price := new.price_cents::numeric / 100;
  elsif new.price is distinct from old.price then
    new.price_cents := greatest(0, round(coalesce(new.price, 0)::numeric * 100)::integer);
  end if;

  if new.status = 'published' and new.published_at is null then
    new.published_at := now();
  end if;

  return new;
end;
$$;

drop trigger if exists sync_series_price_fields_trigger on public.series;
create trigger sync_series_price_fields_trigger
before insert or update of price, price_cents, status
on public.series
for each row execute function public.sync_series_price_fields();

create table if not exists public.series_slug_redirects (
  id bigint generated by default as identity primary key,
  series_id text not null,
  old_slug text not null,
  new_slug text not null,
  created_at timestamptz not null default now(),
  constraint series_slug_redirects_old_slug_check check (length(trim(old_slug)) > 0),
  constraint series_slug_redirects_new_slug_check check (length(trim(new_slug)) > 0),
  constraint series_slug_redirects_distinct_check check (lower(old_slug) <> lower(new_slug))
);

create unique index if not exists series_slug_redirects_old_slug_unique_idx
  on public.series_slug_redirects (old_slug);

create index if not exists series_slug_redirects_series_id_idx
  on public.series_slug_redirects (series_id, created_at desc);

alter table public.series_slug_redirects enable row level security;
revoke all on table public.series_slug_redirects from anon, authenticated;
revoke all on sequence public.series_slug_redirects_id_seq from anon, authenticated;
