create table if not exists public.public_channel_post_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  channel_id bigint not null,
  channel_username text,
  channel_title text,
  message_id bigint not null,
  message_date timestamptz,
  author_signature text,
  message_type text,
  text text,
  caption text,
  raw_update jsonb not null default '{}'::jsonb
);

alter table public.public_channel_post_audit enable row level security;

create index if not exists public_channel_post_audit_created_at_idx
  on public.public_channel_post_audit (created_at desc);

create index if not exists public_channel_post_audit_channel_id_idx
  on public.public_channel_post_audit (channel_id, created_at desc);

create index if not exists public_channel_post_audit_message_id_idx
  on public.public_channel_post_audit (message_id);

create index if not exists public_channel_post_audit_message_type_idx
  on public.public_channel_post_audit (message_type, created_at desc);
