-- Private server-managed carts and coupon rules.
create table if not exists public.shopping_carts (
  user_id text primary key,
  item_ids text[] not null default '{}'::text[],
  coupon_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shopping_carts_item_count_check check (cardinality(item_ids) <= 50)
);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  description text,
  discount_type text,
  discount_value numeric(12,2),
  minimum_amount numeric(12,2) not null default 0,
  starts_at timestamptz,
  ends_at timestamptz,
  usage_limit integer,
  per_user_limit integer not null default 1,
  eligible_series_ids text[] not null default '{}'::text[],
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Preserve the legacy coupons table while expanding it to the server-validated model.
alter table public.coupons
  add column if not exists description text,
  add column if not exists discount_type text,
  add column if not exists discount_value numeric(12,2),
  add column if not exists minimum_amount numeric(12,2) not null default 0,
  add column if not exists starts_at timestamptz,
  add column if not exists ends_at timestamptz,
  add column if not exists usage_limit integer,
  add column if not exists per_user_limit integer not null default 1,
  add column if not exists eligible_series_ids text[] not null default '{}'::text[],
  add column if not exists active boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

update public.coupons
set
  code = upper(code),
  discount_type = coalesce(
    discount_type,
    case when coalesce(discount_fixed, 0) > 0 then 'fixed' else 'percentage' end
  ),
  discount_value = coalesce(
    discount_value,
    case
      when coalesce(discount_fixed, 0) > 0 then discount_fixed
      when coalesce(discount_percent, 0) > 0 then discount_percent
      else 1
    end
  ),
  ends_at = coalesce(ends_at, valid_until at time zone 'America/Sao_Paulo'),
  usage_limit = coalesce(usage_limit, max_uses),
  active = active and (discount_value is not null or coalesce(discount_fixed, 0) > 0 or coalesce(discount_percent, 0) > 0),
  updated_at = now();

alter table public.coupons
  alter column discount_type set not null,
  alter column discount_value set not null,
  drop constraint if exists coupons_code_check,
  add constraint coupons_code_check check (code = upper(code) and code ~ '^[A-Z0-9_-]{3,32}$'),
  drop constraint if exists coupons_discount_type_check,
  add constraint coupons_discount_type_check check (discount_type in ('percentage', 'fixed')),
  drop constraint if exists coupons_discount_value_check,
  add constraint coupons_discount_value_check check (
    discount_value > 0
    and (discount_type <> 'percentage' or discount_value <= 100)
  ),
  drop constraint if exists coupons_minimum_amount_check,
  add constraint coupons_minimum_amount_check check (minimum_amount >= 0),
  drop constraint if exists coupons_usage_limit_check,
  add constraint coupons_usage_limit_check check (usage_limit is null or usage_limit > 0),
  drop constraint if exists coupons_per_user_limit_check,
  add constraint coupons_per_user_limit_check check (per_user_limit > 0),
  drop constraint if exists coupons_period_check,
  add constraint coupons_period_check check (ends_at is null or starts_at is null or ends_at > starts_at);

create table if not exists public.coupon_redemptions (
  id bigint generated by default as identity primary key,
  coupon_code text not null references public.coupons(code) on update cascade on delete restrict,
  user_id text not null,
  order_id text not null references public.payment_orders(order_id) on delete cascade,
  discount_amount numeric(12,2) not null,
  status text not null default 'reserved',
  created_at timestamptz not null default now(),
  applied_at timestamptz,
  reversed_at timestamptz,
  constraint coupon_redemptions_discount_check check (discount_amount > 0),
  constraint coupon_redemptions_status_check check (status in ('reserved', 'applied', 'reversed')),
  constraint coupon_redemptions_order_unique unique (order_id)
);

alter table public.payment_orders
  add column if not exists subtotal numeric(12,2) not null default 0,
  add column if not exists discount_amount numeric(12,2) not null default 0,
  add column if not exists coupon_code text;

alter table public.payment_orders
  drop constraint if exists payment_orders_discount_check,
  add constraint payment_orders_discount_check check (
    subtotal >= 0 and discount_amount >= 0 and amount >= 0 and discount_amount <= subtotal
  );

update public.payment_orders
set subtotal = amount
where subtotal = 0 and amount > 0;

create index if not exists shopping_carts_updated_at_idx on public.shopping_carts(updated_at desc);
create index if not exists coupons_active_period_idx on public.coupons(active, starts_at, ends_at);
create index if not exists coupon_redemptions_coupon_status_idx on public.coupon_redemptions(coupon_code, status);
create index if not exists coupon_redemptions_user_coupon_idx on public.coupon_redemptions(user_id, coupon_code, created_at desc);
create index if not exists payment_orders_coupon_code_idx on public.payment_orders(coupon_code) where coupon_code is not null;

create or replace function public.reserve_coupon_redemption(
  p_coupon_code text,
  p_user_id text,
  p_order_id text,
  p_discount_amount numeric
)
returns bigint
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_coupon public.coupons%rowtype;
  v_usage_count bigint;
  v_user_count bigint;
  v_redemption_id bigint;
begin
  perform pg_advisory_xact_lock(hashtext(p_coupon_code));

  select * into v_coupon
  from public.coupons
  where code = p_coupon_code
    and active = true
    and (starts_at is null or starts_at <= now())
    and (ends_at is null or ends_at > now())
  for update;

  if not found then
    raise exception 'Cupom invalido, inativo ou expirado';
  end if;

  select
    count(*) filter (
      where status = 'applied'
        or (status = 'reserved' and created_at > now() - interval '30 minutes')
    ),
    count(*) filter (
      where user_id = p_user_id
        and (
          status = 'applied'
          or (status = 'reserved' and created_at > now() - interval '30 minutes')
        )
    )
  into v_usage_count, v_user_count
  from public.coupon_redemptions
  where coupon_code = p_coupon_code;

  if v_coupon.usage_limit is not null and v_usage_count >= v_coupon.usage_limit then
    raise exception 'Este cupom atingiu o limite de usos';
  end if;

  if v_user_count >= v_coupon.per_user_limit then
    raise exception 'Este cupom ja foi utilizado por esta conta';
  end if;

  insert into public.coupon_redemptions (
    coupon_code,
    user_id,
    order_id,
    discount_amount,
    status
  ) values (
    p_coupon_code,
    p_user_id,
    p_order_id,
    p_discount_amount,
    'reserved'
  )
  returning id into v_redemption_id;

  return v_redemption_id;
end;
$$;

alter table public.shopping_carts enable row level security;
alter table public.coupons enable row level security;
alter table public.coupon_redemptions enable row level security;

revoke all on table public.shopping_carts from anon, authenticated;
revoke all on table public.coupons from anon, authenticated;
revoke all on table public.coupon_redemptions from anon, authenticated;
revoke all on sequence public.coupon_redemptions_id_seq from anon, authenticated;
revoke all on function public.reserve_coupon_redemption(text, text, text, numeric) from public, anon, authenticated;
grant execute on function public.reserve_coupon_redemption(text, text, text, numeric) to service_role;
