-- Consent-aware, single-attempt recovery for valid pending checkouts.
create extension if not exists pg_cron with schema pg_catalog;

alter table public.payment_orders
  add column if not exists recovery_eligible_at timestamptz,
  add column if not exists checkout_expires_at timestamptz,
  add column if not exists checkout_last_seen_at timestamptz,
  add column if not exists recovery_sent_at timestamptz,
  add column if not exists recovered_at timestamptz;

update public.payment_orders
set
  recovery_eligible_at = coalesce(recovery_eligible_at, created_at + interval '60 minutes'),
  checkout_expires_at = coalesce(
    checkout_expires_at,
    qr_code_expires_at,
    created_at + interval '24 hours'
  )
where recovery_eligible_at is null
   or checkout_expires_at is null;

create index if not exists payment_orders_recovery_candidates_idx
  on public.payment_orders (recovery_eligible_at, checkout_last_seen_at, last_event_at, created_at)
  where status in ('created', 'pending', 'pending_payment', 'in_process', 'pending_review')
    and recovery_sent_at is null;

create table if not exists public.user_notification_preferences (
  user_id text primary key,
  payments_enabled boolean not null default true,
  purchases_enabled boolean not null default true,
  releases_enabled boolean not null default false,
  promotions_enabled boolean not null default false,
  series_available_enabled boolean not null default false,
  checkout_abandoned_enabled boolean not null default false,
  referrals_enabled boolean not null default false,
  marketing_enabled boolean not null default false,
  notification_channel text not null default 'telegram',
  bot_started_at timestamptz,
  marketing_consented_at timestamptz,
  recovery_consented_at timestamptz,
  consent_version text,
  last_change_source text not null default 'system',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_notification_preferences_channel_check
    check (notification_channel in ('telegram', 'none'))
);

create table if not exists public.notification_preference_audit (
  id bigint generated by default as identity primary key,
  user_id text not null,
  change_source text not null,
  previous_preferences jsonb,
  new_preferences jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.checkout_recoveries (
  order_id text primary key references public.payment_orders(order_id) on delete cascade,
  user_id text not null,
  status text not null default 'queued',
  detected_at timestamptz not null default now(),
  send_attempted_at timestamptz,
  sent_at timestamptz,
  recovered_at timestamptz,
  skipped_at timestamptz,
  skip_reason text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint checkout_recoveries_status_check
    check (status in ('queued', 'sent', 'recovered', 'skipped', 'failed'))
);

create table if not exists public.checkout_recovery_runtime (
  id smallint primary key default 1 check (id = 1),
  secret_hash text not null,
  created_at timestamptz not null default now(),
  rotated_at timestamptz not null default now()
);

create index if not exists checkout_recoveries_user_sent_idx
  on public.checkout_recoveries (user_id, sent_at desc)
  where sent_at is not null;

create index if not exists checkout_recoveries_status_detected_idx
  on public.checkout_recoveries (status, detected_at);

create index if not exists notification_preference_audit_user_idx
  on public.notification_preference_audit (user_id, created_at desc);

create or replace function public.audit_notification_preference_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' or to_jsonb(new) is distinct from to_jsonb(old) then
    insert into public.notification_preference_audit (
      user_id,
      change_source,
      previous_preferences,
      new_preferences
    ) values (
      new.user_id,
      new.last_change_source,
      case when tg_op = 'UPDATE' then to_jsonb(old) else null end,
      to_jsonb(new)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists user_notification_preferences_audit_trg
  on public.user_notification_preferences;
create trigger user_notification_preferences_audit_trg
after insert or update on public.user_notification_preferences
for each row execute function public.audit_notification_preference_change();

create or replace function public.claim_checkout_recovery_candidates(
  p_limit integer default 25,
  p_delay_minutes integer default 60,
  p_max_age_hours integer default 24,
  p_user_cooldown_hours integer default 168
)
returns table (
  order_id text,
  user_id text,
  chat_id text,
  payment_method text,
  amount numeric,
  items jsonb,
  checkout_url text,
  ticket_url text,
  created_at timestamptz,
  checkout_expires_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 25), 1), 100);
  v_delay interval := make_interval(mins => least(greatest(coalesce(p_delay_minutes, 60), 15), 10080));
  v_max_age interval := make_interval(hours => least(greatest(coalesce(p_max_age_hours, 24), 1), 720));
  v_user_cooldown interval := make_interval(hours => least(greatest(coalesce(p_user_cooldown_hours, 168), 1), 2160));
begin
  perform pg_advisory_xact_lock(hashtext('checkout-recovery-claim-v1'));

  return query
  with eligible as (
    select
      po.order_id,
      po.user_id,
      po.chat_id,
      po.payment_method,
      po.amount,
      po.items,
      po.checkout_url,
      po.ticket_url,
      po.created_at,
      coalesce(po.checkout_expires_at, po.qr_code_expires_at, po.created_at + v_max_age) as effective_expires_at,
      row_number() over (partition by po.user_id order by po.created_at desc) as user_rank
    from public.payment_orders po
    join public.user_notification_preferences pref
      on pref.user_id = po.user_id
    where po.status in ('created', 'pending', 'pending_payment', 'in_process', 'pending_review')
      and po.confirmed_at is null
      and po.paid_at is null
      and po.canceled_at is null
      and po.rejected_at is null
      and po.recovery_sent_at is null
      and coalesce(po.recovery_eligible_at, po.updated_at + v_delay) <= now()
      and coalesce(po.checkout_last_seen_at, po.last_event_at, po.updated_at, po.created_at) <= now() - v_delay
      and coalesce(po.checkout_expires_at, po.qr_code_expires_at, po.created_at + v_max_age) > now()
      and po.created_at >= now() - v_max_age
      and jsonb_typeof(po.items) = 'array'
      and jsonb_array_length(po.items) > 0
      and pref.bot_started_at is not null
      and pref.checkout_abandoned_enabled = true
      and pref.recovery_consented_at is not null
      and pref.notification_channel = 'telegram'
      and not exists (
        select 1
        from public.checkout_recoveries existing
        where existing.order_id = po.order_id
      )
      and not exists (
        select 1
        from public.checkout_recoveries recent
        where recent.user_id = po.user_id
          and recent.sent_at > now() - v_user_cooldown
      )
      and not exists (
        select 1
        from jsonb_array_elements(po.items) item(value)
        join public.entitlements entitlement
          on entitlement.series_id::text = coalesce(
            item.value->>'id',
            item.value->>'series_id',
            item.value->>'serie_id'
          )
        where entitlement.user_id = po.user_id
          and entitlement.status = 'active'
      )
  ), claimed as (
    insert into public.checkout_recoveries (order_id, user_id, status, detected_at)
    select eligible.order_id, eligible.user_id, 'queued', now()
    from eligible
    where eligible.user_rank = 1
    order by eligible.created_at
    limit v_limit
    on conflict on constraint checkout_recoveries_pkey do nothing
    returning checkout_recoveries.order_id as claimed_order_id
  )
  select
    eligible.order_id,
    eligible.user_id,
    eligible.chat_id,
    eligible.payment_method,
    eligible.amount,
    eligible.items,
    eligible.checkout_url,
    eligible.ticket_url,
    eligible.created_at,
    eligible.effective_expires_at
  from eligible
  join claimed on claimed.claimed_order_id = eligible.order_id
  order by eligible.created_at;
end;
$$;

create or replace function public.validate_checkout_recovery_secret(p_secret text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.checkout_recovery_runtime runtime
    where runtime.id = 1
      and runtime.secret_hash = encode(extensions.digest(coalesce(p_secret, ''), 'sha256'), 'hex')
  );
$$;

alter table public.user_notification_preferences enable row level security;
alter table public.notification_preference_audit enable row level security;
alter table public.checkout_recoveries enable row level security;
alter table public.checkout_recovery_runtime enable row level security;

revoke all on table public.user_notification_preferences from public, anon, authenticated;
revoke all on table public.notification_preference_audit from public, anon, authenticated;
revoke all on sequence public.notification_preference_audit_id_seq from public, anon, authenticated;
revoke all on table public.checkout_recoveries from public, anon, authenticated;
revoke all on table public.checkout_recovery_runtime from public, anon, authenticated;
revoke all on function public.audit_notification_preference_change() from public, anon, authenticated;
revoke all on function public.claim_checkout_recovery_candidates(integer, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.validate_checkout_recovery_secret(text) from public, anon, authenticated;

grant all on table public.user_notification_preferences to service_role;
grant all on table public.notification_preference_audit to service_role;
grant usage, select on sequence public.notification_preference_audit_id_seq to service_role;
grant all on table public.checkout_recoveries to service_role;
grant all on table public.checkout_recovery_runtime to service_role;
grant execute on function public.claim_checkout_recovery_candidates(integer, integer, integer, integer) to service_role;
grant execute on function public.validate_checkout_recovery_secret(text) to service_role;

do $$
declare
  v_secret text := encode(extensions.gen_random_bytes(32), 'hex');
begin
  insert into public.checkout_recovery_runtime (id, secret_hash)
  values (1, encode(extensions.digest(v_secret, 'sha256'), 'hex'))
  on conflict (id) do nothing;

  if not exists (select 1 from vault.secrets where name = 'checkout_recovery_secret') then
    perform vault.create_secret(
      v_secret,
      'checkout_recovery_secret',
      'Header interno da rotina de recuperacao de checkout'
    );
  end if;
end;
$$;

do $$
declare
  v_job_id bigint;
begin
  select jobid into v_job_id
  from cron.job
  where jobname = 'checkout-recovery-every-15-minutes';

  if v_job_id is not null then
    perform cron.unschedule(v_job_id);
  end if;

  perform cron.schedule(
    'checkout-recovery-every-15-minutes',
    '*/15 * * * *',
    $cron$
      select net.http_post(
        url := 'https://uyyeascxvnrkjtlygdoe.supabase.co/functions/v1/bot-unificado/api?action=checkout-recovery-run',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-checkout-recovery-secret', (
            select decrypted_secret
            from vault.decrypted_secrets
            where name = 'checkout_recovery_secret'
            limit 1
          )
        ),
        body := '{"source":"supabase_cron"}'::jsonb,
        timeout_milliseconds := 60000
      );
    $cron$
  );
end;
$$;
