alter table public.payment_orders
  add column if not exists delivery_status text not null default 'pending',
  add column if not exists delivery_attempts integer not null default 0,
  add column if not exists delivered_item_ids jsonb not null default '[]'::jsonb,
  add column if not exists delivery_started_at timestamptz,
  add column if not exists delivery_completed_at timestamptz,
  add column if not exists delivery_last_error text,
  add column if not exists delivery_notification_sent_at timestamptz;

create index if not exists payment_orders_delivery_status_idx
  on public.payment_orders (delivery_status, updated_at desc);

create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null,
  user_id text not null,
  series_id text,
  order_id text,
  session_id text,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.app_events enable row level security;

drop policy if exists "Deny all public access" on public.app_events;
create policy "Deny all public access"
  on public.app_events
  for all
  to public
  using (false)
  with check (false);

create index if not exists app_events_created_at_idx
  on public.app_events (created_at desc);

create index if not exists app_events_event_name_created_at_idx
  on public.app_events (event_name, created_at desc);

create index if not exists app_events_user_id_created_at_idx
  on public.app_events (user_id, created_at desc);

create index if not exists app_events_order_id_idx
  on public.app_events (order_id)
  where order_id is not null;
